version: 0.2

env:
  parameter-store:
    SECRET_KEY: /CodeBuild/SECRET_KEY

phases:
  install:
    commands:
      - "echo Installing"
      - "apt update"
      - "apt install python3 python3-pip"
  pre_build:
    commands:
      - "echo Setup"
      - "pip3 install -r requirements.txt"
      - "cd src"
      - "rm tests/no_test_int.py tests/test_int_update.py"
  build:
    commands:
      - "echo Testing"
      - "python3 -m pytest"
  post_build:
    commands:
      - "echo Done!"

artifacts:
  files:
    - htmlcov/*
